CC=g++
CFLAG=-g -Wno-deprecated

e4_2: e4_2.cpp
	${CC} ${CFLAG} -o $@ $<

e4_3: e4_3.cpp
	${CC} ${CFLAG} -o $@ $<

e4_4: e4_4.cpp
	${CC} ${CFLAG} -o $@ $<

e4_5: e4_5.cpp
	${CC} ${CFLAG} -o $@ $<

e4_6: e4_6.cpp
	${CC} ${CFLAG} -o $@ $<

e4_7: e4_7.cpp
	${CC} ${CFLAG} -o $@ $<

e4_8: e4_8.cpp
	${CC} ${CFLAG} -o $@ $<

e4_9: e4_9.cpp
	${CC} ${CFLAG} -o $@ $<

e4_10: e4_10.cpp
	${CC} ${CFLAG} -o $@ $<

e4_11: e4_11.cpp
	${CC} ${CFLAG} -o $@ $<

e4_12: e4_12.cpp
	${CC} ${CFLAG} -o $@ $<

e4_13: e4_13.cpp
	${CC} ${CFLAG} -o $@ $<

e4_14: e4_14.cpp
	${CC} ${CFLAG} -o $@ $<

e4_15: e4_15.cpp
	${CC} ${CFLAG} -o $@ $<

e4_16: e4_16.cpp
	${CC} ${CFLAG} -o $@ $<

e4_17: e4_17.cpp
	${CC} ${CFLAG} -o $@ $<

e4_18: e4_18.cpp
	${CC} ${CFLAG} -o $@ $<

e4_19: e4_19.cpp
	${CC} ${CFLAG} -o $@ $<

e4_20: e4_20.cpp
	${CC} ${CFLAG} -o $@ $<

e4_21: e4_21.cpp
	${CC} ${CFLAG} -o $@ $<
