CC=g++
CFLAG=-g -Wno-deprecated

e4_2: e4_2.cpp
	${CC} ${CFLAG} -o $@ $<

e4_3: e4_3.cpp
	${CC} ${CFLAG} -o $@ $<

e4_4: e4_4.cpp
	${CC} ${CFLAG} -o $@ $<

e4_5: e4_5.cpp
	${CC} ${CFLAG} -o $@ $<

e4_6: e4_6.cpp
	${CC} ${CFLAG} -o $@ $<

e4_7: e4_7.cpp
	${CC} ${CFLAG} -o $@ $<

e4_8: e4_8.cpp
	${CC} ${CFLAG} -o $@ $<

e4_9: e4_9.cpp
	${CC} ${CFLAG} -o $@ $<

e4_10: e4_10.cpp
	${CC} ${CFLAG} -o $@ $<

e4_11: e4_11.cpp
	${CC} ${CFLAG} -o $@ $<
