CFLAG=-g -Wno-deprecated

e3_2: e3_2.cpp
e3_3: e3_3.cpp
e3_4: e3_4.cpp
e3_5: e3_5.cpp
e3_6: e3_6.cpp
e3_7: e3_7.cpp
e3_8: e3_8.cpp
e3_9: e3_9.cpp
e3_10: e3_10.cpp
e3_11: e3_11.cpp
	g++ ${CFLAG} -o $@ $<
