CFLAG=-g -Wno-deprecated

t4_4_1_1: t4_4_1_1.cpp
	g++ ${CFLAG} -o $@ $<
t4_4_1_2: t4_4_1_2.cpp
	g++ ${CFLAG} -o $@ $<
t4_4_2_1: t4_4_2_1.cpp
	g++ ${CFLAG} -o $@ $<
t4_4_2_3: t4_4_2_3.cpp
	g++ ${CFLAG} -o $@ $<
t4_5: t4_5.cpp
	g++ ${CFLAG} -o $@ $<
t4_6: t4_6.cpp
	g++ ${CFLAG} -o $@ $<
t4_6_2: t4_6_2.cpp
	g++ ${CFLAG} -o $@ $<
t4_6_3: t4_6_3.cpp
	g++ ${CFLAG} -o $@ $<
t4_6_3_bleep: t4_6_3_bleep.cpp
	g++ ${CFLAG} -o $@ $<