CFLAG=-g -Wno-deprecated

t5_3: t5_3.cpp
	g++ ${CFLAG} -o $@ $<

t5_5: t5_5.cpp
	g++ ${CFLAG} -o $@ $<

t5_6_1: t5_6_1.cpp
	g++ ${CFLAG} -o $@ $<

t5_6_2: t5_6_2.cpp
	g++ ${CFLAG} -o $@ $<

t5_6_3: t5_6_3.cpp
	g++ ${CFLAG} -Wall -o $@ $<

t5_6_4: t5_6_4.cpp
	g++ ${CFLAG} -Wall -o $@ $<
