CC=g++
CFLAG=-g -Wno-deprecated

d4_1: d4_1.cpp
	${CC} ${CFLAG} -o $@ $<

d4_2: d4_2.cpp
	${CC} ${CFLAG} -o $@ $<

d4_3: d4_3.cpp
	${CC} ${CFLAG} -o $@ $<

d4_4: d4_4.cpp
	${CC} ${CFLAG} -o $@ $<

d4_5: d4_5.cpp
	${CC} ${CFLAG} -o $@ $<

d4_6: d4_6.cpp
	${CC} ${CFLAG} -o $@ $<

d4_7: d4_7.cpp
	${CC} ${CFLAG} -o $@ $<

d4_8: d4_8.cpp
	${CC} ${CFLAG} -o $@ $<

d4_9: d4_9.cpp
	${CC} ${CFLAG} -o $@ $<

d4_10: d4_10.cpp
	${CC} ${CFLAG} -o $@ $<

d4_11: d4_11.cpp
	${CC} ${CFLAG} -o $@ $<
