hello_world: hello_world.cpp
	g++ -g -Wno-deprecated -o hello_world hello_world.cpp

try3_3: try3_3.cpp
	g++ -g -Wno-deprecated -o try3_3 try3_3.cpp

try3_4: try3_4.cpp
	g++ -g -Wno-deprecated -o try3_4 try3_4.cpp

try3_5: try3_5.cpp
	g++ -g -Wno-deprecated -o try3_5 try3_5.cpp

try3_6: try3_6.cpp
	g++ -g -Wno-deprecated -o try3_6 try3_6.cpp