try3_3: try3_3.cpp
	g++ -g -Wno-deprecated -o try3_3 try3_3.cpp

try3_4: try3_4.cpp
	g++ -g -Wno-deprecated -o try3_4 try3_4.cpp

try3_5: try3_5.cpp
	g++ -g -Wno-deprecated -o try3_5 try3_5.cpp

try3_6: try3_6.cpp
	g++ -g -Wno-deprecated -o try3_6 try3_6.cpp

try3_8: try3_8.cpp
	g++ -g -Wno-deprecated -o try3_8 try3_8.cpp

try3_9: try3_9.cpp
	g++ -g -Wno-deprecated -Wall -o try3_9 try3_9.cpp